SELECT COUNT(*) FROM cast_info WHERE movie_id > 205 LIMIT 10;
SELECT COUNT(*) FROM cast_info LIMIT 10;
SELECT COUNT(*) FROM cast_info WHERE movie_id < 645 LIMIT 10;
SELECT COUNT(*) FROM info_type LIMIT 10;
SELECT COUNT(*) FROM movie_info LIMIT 10;
SELECT COUNT(*) FROM movie_keyword WHERE movie_id > 557 LIMIT 10;
SELECT COUNT(*) FROM movie_keyword WHERE movie_id < 214 LIMIT 10;
SELECT COUNT(*) FROM movie_keyword LIMIT 10;
SELECT COUNT(*) FROM movie_info WHERE movie_id > 554 LIMIT 10;
SELECT COUNT(*) FROM title LIMIT 10;
SELECT COUNT(*) FROM cast_info WHERE movie_id > 386 LIMIT 10;
SELECT COUNT(*) FROM cast_info WHERE movie_id < 431 LIMIT 10;
SELECT COUNT(*) FROM title WHERE production_year < 1999 LIMIT 10;
SELECT COUNT(*) FROM movie_info WHERE movie_id < 394 LIMIT 10;
SELECT COUNT(*) FROM movie_info WHERE movie_id > 359 LIMIT 10;
SELECT COUNT(*) FROM info_type WHERE id > 135 LIMIT 10;
SELECT COUNT(*) FROM info_type WHERE id < 562 LIMIT 10;
SELECT COUNT(*) FROM movie_info WHERE movie_id < 452 LIMIT 10;
SELECT COUNT(*) FROM info_type WHERE id < 236 LIMIT 10;
SELECT COUNT(*) FROM cast_info WHERE movie_id < 539 LIMIT 10;
SELECT COUNT(*) FROM movie_keyword WHERE movie_id < 453 LIMIT 10;
SELECT COUNT(*) FROM title WHERE production_year < 1975 LIMIT 10;
SELECT COUNT(*) FROM movie_keyword WHERE movie_id < 315 LIMIT 10;
SELECT COUNT(*) FROM cast_info WHERE movie_id > 93 LIMIT 10;
SELECT COUNT(*) FROM movie_info WHERE movie_id < 350 LIMIT 10;
SELECT COUNT(*) FROM info_type WHERE id < 804 LIMIT 10;
SELECT COUNT(*) FROM cast_info WHERE movie_id > 651 LIMIT 10;
SELECT COUNT(*) FROM title WHERE production_year < 1933 LIMIT 10;
SELECT COUNT(*) FROM movie_keyword WHERE movie_id > 801 LIMIT 10;
SELECT COUNT(*) FROM cast_info WHERE movie_id < 430 LIMIT 10;
SELECT COUNT(*) FROM title WHERE production_year > 1975 LIMIT 10;
SELECT COUNT(*) FROM cast_info WHERE movie_id < 652 LIMIT 10;
SELECT COUNT(*) FROM info_type WHERE id > 574 LIMIT 10;
SELECT COUNT(*) FROM title WHERE production_year < 1985 LIMIT 10;
SELECT COUNT(*) FROM info_type WHERE id < 321 LIMIT 10;
SELECT COUNT(*) FROM title WHERE production_year > 1947 LIMIT 10;
SELECT COUNT(*) FROM title WHERE production_year < 1960 LIMIT 10;
SELECT COUNT(*) FROM movie_info WHERE movie_id < 31 LIMIT 10;
SELECT COUNT(*) FROM movie_keyword WHERE movie_id < 30 LIMIT 10;
SELECT COUNT(*) FROM cast_info WHERE movie_id < 848 LIMIT 10;
SELECT COUNT(*) FROM info_type WHERE id < 815 LIMIT 10;
SELECT COUNT(*) FROM info_type WHERE id > 243 LIMIT 10;
SELECT COUNT(*) FROM title WHERE production_year < 1956 LIMIT 10;
SELECT COUNT(*) FROM movie_keyword WHERE movie_id > 735 LIMIT 10;
SELECT COUNT(*) FROM cast_info WHERE movie_id < 282 LIMIT 10;
SELECT COUNT(*) FROM movie_keyword WHERE movie_id < 67 LIMIT 10;
SELECT COUNT(*) FROM info_type WHERE id > 183 LIMIT 10;
SELECT COUNT(*) FROM cast_info WHERE movie_id > 474 LIMIT 10;
SELECT COUNT(*) FROM movie_info WHERE movie_id > 313 LIMIT 10;
SELECT COUNT(*) FROM movie_keyword WHERE movie_id > 277 LIMIT 10;
SELECT COUNT(*) FROM title WHERE production_year < 1907 LIMIT 10;
SELECT COUNT(*) FROM info_type WHERE id < 769 LIMIT 10;
