SELECT COUNT(*) FROM title t,cast_info ci WHERE t.id=ci.movie_id AND ci.person_id<3194645;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_info_idx mi_idx WHERE t.id=mc.movie_id AND t.id=mi_idx.movie_id AND mc.company_id<77942 AND mc.company_type_id>1;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id<71692;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<9749 AND mc.company_type_id>1;
SELECT COUNT(*) FROM title t,movie_keyword mk WHERE t.id=mk.movie_id AND mk.keyword_id<1029;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<80833 AND mc.company_type_id=1;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>2237;
SELECT COUNT(*) FROM title t,movie_companies mc WHERE t.id=mc.movie_id AND mc.company_id<213849 AND mc.company_type_id>1;
SELECT COUNT(*) FROM title t,movie_keyword mk WHERE t.id=mk.movie_id AND mk.keyword_id<80578;
SELECT COUNT(*) FROM title t,movie_info mi,movie_info_idx mi_idx WHERE t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.production_year>1978 AND mi.info_type_id=3;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id<1436321;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id>1127 AND mc.company_type_id=1;
SELECT COUNT(*) FROM title t,movie_companies mc WHERE t.id=mc.movie_id AND t.production_year<1996;
SELECT COUNT(*) FROM title t,movie_info_idx mi_idx,movie_keyword mk WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND mi_idx.info_type_id=100 AND mk.keyword_id>430;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>19819;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<11393 AND mc.company_type_id>1;
SELECT COUNT(*) FROM title t,movie_info mi,movie_info_idx mi_idx WHERE t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.production_year<1965 AND mi.info_type_id<90;
SELECT COUNT(*) FROM title t,movie_companies mc WHERE t.id=mc.movie_id AND mc.company_id>213;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id>868 AND mc.company_type_id=2;
SELECT COUNT(*) FROM title t,movie_companies mc WHERE t.id=mc.movie_id AND t.kind_id<4 AND t.production_year>1910 AND mc.company_id>1461 AND mc.company_type_id=2;
SELECT COUNT(*) FROM title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.kind_id<7 AND t.production_year>1961 AND mi_idx.info_type_id<101;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_info_idx mi_idx WHERE t.id=mc.movie_id AND t.id=mi_idx.movie_id AND mc.company_id<11373;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id=34013;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>26476;
SELECT COUNT(*) FROM title t,movie_info_idx mi_idx,movie_keyword mk WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND t.production_year>2012 AND mi_idx.info_type_id>100;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id<5374;
SELECT COUNT(*) FROM title t,movie_companies mc,cast_info ci WHERE t.id=mc.movie_id AND t.id=ci.movie_id AND mc.company_type_id>1 AND ci.person_id<394300;
SELECT COUNT(*) FROM title t,cast_info ci,movie_info mi WHERE t.id=ci.movie_id AND t.id=mi.movie_id AND t.production_year>2010 AND mi.info_type_id>3;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id=32057 AND mc.company_type_id<2;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id=90962 AND ci.role_id<10;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id<39210;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id>4434 AND mc.company_type_id=2;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id<1007;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<69853;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id=88122;
SELECT COUNT(*) FROM title t,cast_info ci WHERE t.id=ci.movie_id AND ci.person_id<2279717;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<43106;
SELECT COUNT(*) FROM title t,movie_companies mc,cast_info ci WHERE t.id=mc.movie_id AND t.id=ci.movie_id AND mc.company_id<145 AND mc.company_type_id<2;
SELECT COUNT(*) FROM title t,cast_info ci WHERE t.id=ci.movie_id AND ci.person_id<2626616 AND ci.role_id<10;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_info mi WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND t.kind_id<7 AND mc.company_id<11379;
SELECT COUNT(*) FROM title t,movie_companies mc,cast_info ci WHERE t.id=mc.movie_id AND t.id=ci.movie_id AND t.production_year<2010 AND mc.company_id>33938 AND ci.person_id<1550792;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>10116;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id<1123232;
SELECT COUNT(*) FROM title t,movie_companies mc WHERE t.id=mc.movie_id AND mc.company_id>512 AND mc.company_type_id>1;
SELECT COUNT(*) FROM title t,cast_info ci,movie_info mi WHERE t.id=ci.movie_id AND t.id=mi.movie_id AND t.kind_id<7 AND t.production_year>1970;
SELECT COUNT(*) FROM title t,movie_info mi,movie_keyword mk WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND mk.keyword_id<2697;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id>112526;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id<770925 AND ci.role_id<10;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id=6123;
SELECT COUNT(*) FROM title t,movie_info mi,movie_keyword mk WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND t.kind_id<7 AND mi.info_type_id>16 AND mk.keyword_id<11728;
SELECT COUNT(*) FROM title t,cast_info ci,movie_keyword mk WHERE t.id=ci.movie_id AND t.id=mk.movie_id AND ci.person_id<2566764 AND ci.role_id=1 AND mk.keyword_id<2849;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id=18692;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>2231;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id=14805;
SELECT COUNT(*) FROM title t,movie_info mi,movie_keyword mk WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND t.production_year>2008 AND mi.info_type_id>16;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_info mi WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND t.production_year>2005 AND mc.company_type_id<2 AND mi.info_type_id<7;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<19691 AND mc.company_type_id=2;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_keyword mk WHERE t.id=mc.movie_id AND t.id=mk.movie_id AND t.production_year>1998;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id=14074;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id<57549 AND ci.role_id=1;
SELECT COUNT(*) FROM title t,movie_info mi,movie_keyword mk WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND mi.info_type_id<2 AND mk.keyword_id<96739;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id>27699 AND mc.company_type_id=2;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id=8629;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id>99727;
SELECT COUNT(*) FROM title t,movie_info_idx mi_idx,movie_keyword mk WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND mi_idx.info_type_id=100 AND mk.keyword_id<117;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id<31065;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>6854;
SELECT COUNT(*) FROM title t,cast_info ci WHERE t.id=ci.movie_id AND t.kind_id<7 AND t.production_year>1959;
SELECT COUNT(*) FROM title t,movie_info mi WHERE t.id=mi.movie_id AND t.kind_id<4 AND mi.info_type_id<4;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id<1341245 AND ci.role_id<3;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id<286848;
SELECT COUNT(*) FROM title t,movie_companies mc WHERE t.id=mc.movie_id AND t.kind_id<7 AND t.production_year<1994 AND mc.company_type_id<2;
SELECT COUNT(*) FROM title t,movie_info_idx mi_idx,movie_keyword mk WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND mi_idx.info_type_id<100 AND mk.keyword_id<56903;
SELECT COUNT(*) FROM title t,cast_info ci,movie_keyword mk WHERE t.id=ci.movie_id AND t.id=mk.movie_id AND t.production_year>1913 AND ci.person_id<364441 AND mk.keyword_id<2276;
SELECT COUNT(*) FROM title t,movie_info_idx mi_idx,movie_keyword mk WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND t.production_year>2007 AND mk.keyword_id<38085;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_info_idx mi_idx WHERE t.id=mc.movie_id AND t.id=mi_idx.movie_id AND t.production_year>1914 AND mi_idx.info_type_id=99;
SELECT COUNT(*) FROM title t,movie_info mi WHERE t.id=mi.movie_id AND mi.info_type_id<12;
SELECT COUNT(*) FROM title t,movie_keyword mk WHERE t.id=mk.movie_id AND mk.keyword_id<34121;
SELECT COUNT(*) FROM title t,movie_companies mc WHERE t.id=mc.movie_id AND mc.company_id<171 AND mc.company_type_id=2;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>16691;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id>207995;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id=78435;
SELECT COUNT(*) FROM title t,cast_info ci WHERE t.id=ci.movie_id AND t.production_year<2012 AND ci.person_id<1359374;
SELECT COUNT(*) FROM title t,movie_info mi WHERE t.id=mi.movie_id AND t.production_year<2011 AND mi.info_type_id=16;
SELECT COUNT(*) FROM title t,movie_info mi,movie_keyword mk WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND mk.keyword_id<7477;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id<4519;
SELECT COUNT(*) FROM title t,movie_companies mc WHERE t.id=mc.movie_id AND t.production_year>1955 AND mc.company_id>4730;
SELECT COUNT(*) FROM title t,movie_keyword mk WHERE t.id=mk.movie_id AND mk.keyword_id>1043;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_info mi WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND t.kind_id<4 AND t.production_year<1910 AND mi.info_type_id>73;
SELECT COUNT(*) FROM title t,movie_info_idx mi_idx,movie_keyword mk WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND mi_idx.info_type_id=99 AND mk.keyword_id<108021;
SELECT COUNT(*) FROM title t,movie_info mi,movie_keyword mk WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND t.kind_id<7 AND mi.info_type_id>1 AND mk.keyword_id>2632;
SELECT COUNT(*) FROM title t,movie_info mi WHERE t.id=mi.movie_id AND t.production_year<2010 AND mi.info_type_id<6;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>1312;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>23394;
SELECT COUNT(*) FROM title t,cast_info ci WHERE t.id=ci.movie_id AND t.kind_id<7 AND ci.person_id<2970008;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id>74824;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_info_idx mi_idx WHERE t.id=mc.movie_id AND t.id=mi_idx.movie_id AND t.production_year<2009 AND mc.company_id>12065;
SELECT COUNT(*) FROM title t,cast_info ci,movie_keyword mk WHERE t.id=ci.movie_id AND t.id=mk.movie_id AND ci.person_id<4006715 AND ci.role_id<2 AND mk.keyword_id<1574;
SELECT COUNT(*) FROM title t,cast_info ci,movie_info_idx mi_idx WHERE t.id=ci.movie_id AND t.id=mi_idx.movie_id AND t.kind_id<3 AND t.production_year<1966;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id=2921;
SELECT COUNT(*) FROM title t,cast_info ci WHERE t.id=ci.movie_id AND ci.person_id<2334390 AND ci.role_id=1;
SELECT COUNT(*) FROM title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.production_year<1932 AND mi_idx.info_type_id=99;
SELECT COUNT(*) FROM title t,movie_keyword mk WHERE t.id=mk.movie_id AND mk.keyword_id>1143;
SELECT COUNT(*) FROM title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.production_year>1926;
SELECT COUNT(*) FROM title t,movie_info mi,movie_info_idx mi_idx WHERE t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.kind_id<7 AND t.production_year<1964;
SELECT COUNT(*) FROM title t,movie_info mi,movie_keyword mk WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND t.kind_id<7 AND t.production_year>2012 AND mi.info_type_id>16;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>39961;
SELECT COUNT(*) FROM title t,movie_info_idx mi_idx,movie_keyword mk WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND mk.keyword_id>520;
SELECT COUNT(*) FROM title t,movie_info mi,movie_keyword mk WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND mk.keyword_id<382;
SELECT COUNT(*) FROM title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.production_year>2009 AND mk.keyword_id<844;
SELECT COUNT(*) FROM title t,cast_info ci WHERE t.id=ci.movie_id AND ci.person_id<3918294;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_info_idx mi_idx WHERE t.id=mc.movie_id AND t.id=mi_idx.movie_id AND t.production_year>1996 AND mc.company_id<12594 AND mi_idx.info_type_id>100;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id<2748717;
SELECT COUNT(*) FROM title t,movie_companies mc,cast_info ci WHERE t.id=mc.movie_id AND t.id=ci.movie_id AND mc.company_id<2924 AND mc.company_type_id<2;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id=1684 AND mc.company_type_id=1;
SELECT COUNT(*) FROM title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.kind_id<7 AND t.production_year>1971 AND mi_idx.info_type_id>100;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id=21722;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id>74220;
SELECT COUNT(*) FROM title t,movie_info mi,movie_keyword mk WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND mk.keyword_id<12346;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>16359;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id>7772 AND mc.company_type_id=1;
SELECT COUNT(*) FROM title t,movie_info mi,movie_keyword mk WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND mk.keyword_id<2849;
SELECT COUNT(*) FROM title t,movie_info_idx mi_idx,movie_keyword mk WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND t.kind_id<7 AND mi_idx.info_type_id>100 AND mk.keyword_id<5537;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id=53797 AND mc.company_type_id<2;
SELECT COUNT(*) FROM title t,cast_info ci WHERE t.id=ci.movie_id AND t.kind_id<3 AND t.production_year>2010;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id=26450 AND mc.company_type_id=1;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<44130 AND mc.company_type_id<2;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id<6139;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_info mi WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND t.production_year>0 AND mc.company_id<661 AND mc.company_type_id=1;
SELECT COUNT(*) FROM title t,movie_companies mc WHERE t.id=mc.movie_id AND mc.company_id>13816 AND mc.company_type_id=2;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_info mi WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND t.kind_id<7 AND t.production_year>1997 AND mi.info_type_id>18;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id>225585;
SELECT COUNT(*) FROM title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.production_year>1973 AND mk.keyword_id<2499;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id=10357;
SELECT COUNT(*) FROM title t,cast_info ci,movie_info mi WHERE t.id=ci.movie_id AND t.id=mi.movie_id AND ci.person_id<437596 AND ci.role_id<3;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id<3987;
SELECT COUNT(*) FROM title t,movie_info_idx mi_idx,movie_keyword mk WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND mi_idx.info_type_id<101 AND mk.keyword_id>117;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id=6107;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_keyword mk WHERE t.id=mc.movie_id AND t.id=mk.movie_id AND mc.company_id>1720;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>38705;
SELECT COUNT(*) FROM title t,movie_info_idx mi_idx,movie_keyword mk WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND mk.keyword_id<1037;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>28212;
SELECT COUNT(*) FROM title t,cast_info ci,movie_keyword mk WHERE t.id=ci.movie_id AND t.id=mk.movie_id AND t.production_year>2004 AND ci.role_id<9 AND mk.keyword_id<5654;
SELECT COUNT(*) FROM title t,movie_companies mc,cast_info ci WHERE t.id=mc.movie_id AND t.id=ci.movie_id AND t.production_year<2006 AND ci.person_id<438540 AND ci.role_id=1;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>11685;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id<675588;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<704 AND mc.company_type_id>1;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id<3712293 AND ci.role_id<8;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id=4625 AND mc.company_type_id=1;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id<3169524;
SELECT COUNT(*) FROM title t,movie_info_idx mi_idx,movie_keyword mk WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND mi_idx.info_type_id=101 AND mk.keyword_id<11997;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id>16339 AND mc.company_type_id=2;
SELECT COUNT(*) FROM title t,cast_info ci,movie_keyword mk WHERE t.id=ci.movie_id AND t.id=mk.movie_id AND mk.keyword_id<6069;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id<908593;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<262;
SELECT COUNT(*) FROM title t,movie_companies mc WHERE t.id=mc.movie_id AND mc.company_id<24123;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_info mi WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND t.kind_id<7 AND t.production_year<1965;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id<894226 AND ci.role_id=1;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>9843;
SELECT COUNT(*) FROM title t,cast_info ci WHERE t.id=ci.movie_id AND t.kind_id<7 AND t.production_year>1991 AND ci.person_id<3281297;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id=4776;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id=1861;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id<52025;
SELECT COUNT(*) FROM title t,movie_companies mc WHERE t.id=mc.movie_id AND t.kind_id<7 AND t.production_year<1985 AND mc.company_type_id=2;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>44471;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id<2578472;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id<1613;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id>11264;
SELECT COUNT(*) FROM title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.production_year<2009 AND mk.keyword_id<51928;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<41835;
SELECT COUNT(*) FROM title t,cast_info ci,movie_keyword mk WHERE t.id=ci.movie_id AND t.id=mk.movie_id AND t.kind_id<7 AND t.production_year>2011 AND ci.person_id<175762;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id=5064;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id<14348;
SELECT COUNT(*) FROM title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.kind_id<7 AND t.production_year<2005 AND mk.keyword_id<17591;
SELECT COUNT(*) FROM title t,cast_info ci,movie_info_idx mi_idx WHERE t.id=ci.movie_id AND t.id=mi_idx.movie_id AND t.production_year<2010 AND ci.role_id<10;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>286;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id=37285 AND mc.company_type_id<2;
SELECT COUNT(*) FROM title t,movie_info mi,movie_keyword mk WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND t.production_year<2004 AND mi.info_type_id=6;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id<12762;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id<3125024 AND ci.role_id=1;
SELECT COUNT(*) FROM title t,movie_info mi,movie_keyword mk WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND mi.info_type_id<4 AND mk.keyword_id>4853;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_info mi WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND t.kind_id<7 AND t.production_year>2006 AND mc.company_id<27 AND mc.company_type_id>1 AND mi.info_type_id=6;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>22180;
SELECT COUNT(*) FROM title t,movie_info mi,movie_info_idx mi_idx WHERE t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.production_year>2003 AND mi.info_type_id>18;
SELECT COUNT(*) FROM title t,movie_keyword mk WHERE t.id=mk.movie_id AND mk.keyword_id<229;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>9553;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>2926;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>27850;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id=7108;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_keyword mk WHERE t.id=mc.movie_id AND t.id=mk.movie_id AND mk.keyword_id<5557;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id>14947 AND mc.company_type_id>1;
SELECT COUNT(*) FROM title t,movie_keyword mk WHERE t.id=mk.movie_id AND mk.keyword_id>245;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<3263 AND mc.company_type_id=1;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id=6507;
SELECT COUNT(*) FROM title t,movie_info_idx mi_idx,movie_keyword mk WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND mk.keyword_id>43;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<2191 AND mc.company_type_id>1;
SELECT COUNT(*) FROM title t WHERE t.kind_id<4 AND t.production_year>1994;
SELECT COUNT(*) FROM title t,movie_info_idx mi_idx,movie_keyword mk WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND mk.keyword_id>7990;
SELECT COUNT(*) FROM title t,movie_info_idx mi_idx,movie_keyword mk WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND mi_idx.info_type_id<101 AND mk.keyword_id>7877;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_info_idx mi_idx WHERE t.id=mc.movie_id AND t.id=mi_idx.movie_id AND t.production_year>0 AND mc.company_type_id=1;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id<5182;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_info mi WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND mc.company_id>1070 AND mc.company_type_id=1 AND mi.info_type_id=8;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_info_idx mi_idx WHERE t.id=mc.movie_id AND t.id=mi_idx.movie_id AND t.kind_id<7 AND t.production_year>1987 AND mc.company_type_id=1 AND mi_idx.info_type_id>99;
SELECT COUNT(*) FROM title t,movie_companies mc,cast_info ci WHERE t.id=mc.movie_id AND t.id=ci.movie_id AND t.production_year>0 AND mc.company_id<30240 AND mc.company_type_id<2;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<13981;
SELECT COUNT(*) FROM title t,movie_keyword mk WHERE t.id=mk.movie_id AND mk.keyword_id<245;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<12566 AND mc.company_type_id>1;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id=7577;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id<14963;
SELECT COUNT(*) FROM title t,cast_info ci WHERE t.id=ci.movie_id AND t.production_year<2011 AND ci.role_id<4;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id<21640;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id=65408;
SELECT COUNT(*) FROM title t,movie_info_idx mi_idx,movie_keyword mk WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND t.kind_id<7 AND mk.keyword_id>3311;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_info mi WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND t.production_year<2007 AND mc.company_id>17357 AND mc.company_type_id=2;
SELECT COUNT(*) FROM title t,movie_companies mc WHERE t.id=mc.movie_id AND mc.company_id<184491;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<153122 AND mc.company_type_id>1;
SELECT COUNT(*) FROM title t,movie_companies mc WHERE t.id=mc.movie_id AND t.production_year>2012 AND mc.company_id>19 AND mc.company_type_id=2;
SELECT COUNT(*) FROM title t,movie_companies mc WHERE t.id=mc.movie_id AND mc.company_id<9557;
SELECT COUNT(*) FROM title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.production_year<1985;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>1762;
SELECT COUNT(*) FROM title t,movie_companies mc WHERE t.id=mc.movie_id AND t.production_year<1993 AND mc.company_id>12472 AND mc.company_type_id=2;
SELECT COUNT(*) FROM title t,cast_info ci,movie_info mi WHERE t.id=ci.movie_id AND t.id=mi.movie_id AND ci.person_id<626360 AND ci.role_id<2;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<116570;
SELECT COUNT(*) FROM title t,cast_info ci,movie_keyword mk WHERE t.id=ci.movie_id AND t.id=mk.movie_id AND mk.keyword_id<5887;
SELECT COUNT(*) FROM title t,movie_keyword mk WHERE t.id=mk.movie_id AND mk.keyword_id<14222;
SELECT COUNT(*) FROM title t,movie_info mi,movie_info_idx mi_idx WHERE t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.kind_id<7 AND t.production_year<1995;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id=3166 AND mc.company_type_id<2;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id=3190;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>10607;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id>2849 AND mc.company_type_id>1;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<11790 AND mc.company_type_id=2;
SELECT COUNT(*) FROM title t,cast_info ci,movie_info_idx mi_idx WHERE t.id=ci.movie_id AND t.id=mi_idx.movie_id AND ci.role_id<10 AND mi_idx.info_type_id>99;
SELECT COUNT(*) FROM title t,movie_info mi WHERE t.id=mi.movie_id AND t.kind_id<7 AND t.production_year<1992 AND mi.info_type_id<16;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_keyword mk WHERE t.id=mc.movie_id AND t.id=mk.movie_id AND t.kind_id<7 AND t.production_year>1984 AND mc.company_id<14715;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>23021;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id=4794;
SELECT COUNT(*) FROM title t,movie_companies mc WHERE t.id=mc.movie_id AND t.kind_id<7 AND mc.company_id<92989 AND mc.company_type_id>1;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id=4450;
SELECT COUNT(*) FROM title t,movie_companies mc WHERE t.id=mc.movie_id AND mc.company_id<82208;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id>95736;
SELECT COUNT(*) FROM title t,cast_info ci,movie_info_idx mi_idx WHERE t.id=ci.movie_id AND t.id=mi_idx.movie_id AND ci.person_id<2895384;
SELECT COUNT(*) FROM title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.production_year<2011 AND mk.keyword_id>1002;
SELECT COUNT(*) FROM title t,movie_info_idx mi_idx,movie_keyword mk WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND t.kind_id<6 AND mk.keyword_id>5899;
SELECT COUNT(*) FROM title t,cast_info ci,movie_keyword mk WHERE t.id=ci.movie_id AND t.id=mk.movie_id AND t.kind_id<3 AND ci.person_id<1992934 AND ci.role_id<5;
SELECT COUNT(*) FROM title t,cast_info ci WHERE t.id=ci.movie_id AND t.production_year>2009 AND ci.person_id<2835223 AND ci.role_id<3;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id<3826477 AND ci.role_id=1;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id=37458;
SELECT COUNT(*) FROM title t,movie_companies mc WHERE t.id=mc.movie_id AND t.kind_id<7 AND mc.company_id<1098 AND mc.company_type_id=1;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id=10354;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id=2999;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>11403;
SELECT COUNT(*) FROM title t,cast_info ci,movie_info mi WHERE t.id=ci.movie_id AND t.id=mi.movie_id AND t.kind_id<3 AND t.production_year>1925 AND ci.role_id<3 AND mi.info_type_id=16;
SELECT COUNT(*) FROM title t,movie_info mi,movie_keyword mk WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND mk.keyword_id<5972;
SELECT COUNT(*) FROM title t,cast_info ci,movie_info mi WHERE t.id=ci.movie_id AND t.id=mi.movie_id AND ci.person_id<978992 AND ci.role_id<2;
SELECT COUNT(*) FROM title t,cast_info ci,movie_info_idx mi_idx WHERE t.id=ci.movie_id AND t.id=mi_idx.movie_id AND t.production_year>1902;
SELECT COUNT(*) FROM title t,movie_companies mc WHERE t.id=mc.movie_id AND mc.company_id>1435 AND mc.company_type_id>1;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_info mi WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND t.kind_id<3 AND t.production_year>1999 AND mc.company_type_id<2 AND mi.info_type_id<7;
SELECT COUNT(*) FROM title t,movie_keyword mk WHERE t.id=mk.movie_id AND mk.keyword_id<30237;
SELECT COUNT(*) FROM title t,movie_info mi,movie_keyword mk WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND t.kind_id<7 AND t.production_year>2006 AND mi.info_type_id=7 AND mk.keyword_id<1552;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>1419;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>70318;
SELECT COUNT(*) FROM title t,movie_info_idx mi_idx,movie_keyword mk WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND t.production_year>0 AND mi_idx.info_type_id>100 AND mk.keyword_id>245;
SELECT COUNT(*) FROM title t,cast_info ci WHERE t.id=ci.movie_id AND ci.person_id<2303814;
SELECT COUNT(*) FROM title t,movie_info mi WHERE t.id=mi.movie_id AND t.kind_id<7 AND t.production_year>2007 AND mi.info_type_id>16;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>50099;
SELECT COUNT(*) FROM title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.kind_id<7 AND t.production_year>1960;
SELECT COUNT(*) FROM title t,cast_info ci,movie_info mi WHERE t.id=ci.movie_id AND t.id=mi.movie_id AND ci.person_id<1660824 AND ci.role_id=1 AND mi.info_type_id>16;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id<23303;
SELECT COUNT(*) FROM title t,movie_info mi,movie_keyword mk WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND t.production_year>1987 AND mi.info_type_id=7;
SELECT COUNT(*) FROM title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.production_year<1966 AND mi_idx.info_type_id=99;
SELECT COUNT(*) FROM title t,movie_info mi,movie_info_idx mi_idx WHERE t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.production_year<2001 AND mi.info_type_id>17;
SELECT COUNT(*) FROM title t,movie_info mi,movie_info_idx mi_idx WHERE t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.kind_id<7 AND t.production_year>2004 AND mi.info_type_id<67;
SELECT COUNT(*) FROM title t,cast_info ci WHERE t.id=ci.movie_id AND t.kind_id<2 AND t.production_year>1959;
SELECT COUNT(*) FROM title t,movie_companies mc WHERE t.id=mc.movie_id AND mc.company_id<347;
SELECT COUNT(*) FROM title t,movie_keyword mk WHERE t.id=mk.movie_id AND mk.keyword_id>7491;
SELECT COUNT(*) FROM title t,movie_info_idx mi_idx,movie_keyword mk WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND mk.keyword_id<9079;
SELECT COUNT(*) FROM title t,cast_info ci,movie_info_idx mi_idx WHERE t.id=ci.movie_id AND t.id=mi_idx.movie_id AND t.kind_id<7 AND t.production_year>1976 AND ci.role_id<10 AND mi_idx.info_type_id>100;
SELECT COUNT(*) FROM title t,cast_info ci WHERE t.id=ci.movie_id AND ci.person_id<3473421 AND ci.role_id<2;
SELECT COUNT(*) FROM title t,movie_info mi,movie_info_idx mi_idx WHERE t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.kind_id<3 AND mi.info_type_id>8 AND mi_idx.info_type_id>99;
SELECT COUNT(*) FROM title t,cast_info ci,movie_keyword mk WHERE t.id=ci.movie_id AND t.id=mk.movie_id AND t.production_year<2012 AND mk.keyword_id>2488;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id<1668242;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<11226 AND mc.company_type_id<2;
SELECT COUNT(*) FROM title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.kind_id<7 AND t.production_year<1913 AND mk.keyword_id>335;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_keyword mk WHERE t.id=mc.movie_id AND t.id=mk.movie_id AND mc.company_id>23117 AND mc.company_type_id=2;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id=11241 AND mc.company_type_id>1;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id<37206;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<14490 AND mc.company_type_id=2;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id<26789;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id<1420285;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id>20938 AND mc.company_type_id<2;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_info_idx mi_idx WHERE t.id=mc.movie_id AND t.id=mi_idx.movie_id AND t.kind_id<7 AND t.production_year<2012 AND mi_idx.info_type_id>99;
SELECT COUNT(*) FROM title t,movie_info_idx mi_idx,movie_keyword mk WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND mk.keyword_id>6257;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id<1455638 AND ci.role_id<3;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id=105578 AND mc.company_type_id>1;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>1593;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id=384;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<29121 AND mc.company_type_id<2;
SELECT COUNT(*) FROM title t,cast_info ci,movie_keyword mk WHERE t.id=ci.movie_id AND t.id=mk.movie_id AND t.production_year<2010 AND mk.keyword_id<3354;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_info mi WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND mc.company_id>27 AND mc.company_type_id=1;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id=81741;
SELECT COUNT(*) FROM title t,cast_info ci,movie_info_idx mi_idx WHERE t.id=ci.movie_id AND t.id=mi_idx.movie_id AND t.production_year>1984 AND mi_idx.info_type_id<100;
SELECT COUNT(*) FROM title t,movie_info mi WHERE t.id=mi.movie_id AND t.production_year<2006 AND mi.info_type_id<8;
SELECT COUNT(*) FROM title t,movie_companies mc WHERE t.id=mc.movie_id AND mc.company_id<6158 AND mc.company_type_id=2;
SELECT COUNT(*) FROM title t,movie_info mi,movie_info_idx mi_idx WHERE t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.kind_id<7 AND t.production_year<2004;
SELECT COUNT(*) FROM title t,movie_info_idx mi_idx,movie_keyword mk WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND mk.keyword_id<90934;
SELECT COUNT(*) FROM title t,cast_info ci WHERE t.id=ci.movie_id AND t.production_year>1977 AND ci.role_id<2;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id>29511;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id<2205136 AND ci.role_id<2;
SELECT COUNT(*) FROM title t,movie_info mi,movie_keyword mk WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND t.kind_id<7 AND t.production_year<1991 AND mi.info_type_id>16 AND mk.keyword_id<87135;
SELECT COUNT(*) FROM title t,movie_info mi,movie_info_idx mi_idx WHERE t.id=mi.movie_id AND t.id=mi_idx.movie_id AND mi.info_type_id=2 AND mi_idx.info_type_id=99;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id=31066;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id<3560809;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id=7364;
SELECT COUNT(*) FROM title t,movie_info mi WHERE t.id=mi.movie_id AND t.kind_id<7 AND t.production_year<2002 AND mi.info_type_id>4;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id>530 AND mc.company_type_id>1;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id>125135;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id<2372939 AND ci.role_id=1;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<5379 AND mc.company_type_id<2;
SELECT COUNT(*) FROM title t,movie_info mi,movie_keyword mk WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND t.kind_id<7 AND t.production_year<2003;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>6380;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id<1832532 AND ci.role_id<2;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_keyword mk WHERE t.id=mc.movie_id AND t.id=mk.movie_id AND mc.company_id>61702 AND mk.keyword_id<835;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<71001 AND mc.company_type_id=1;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_info_idx mi_idx WHERE t.id=mc.movie_id AND t.id=mi_idx.movie_id AND mc.company_id>11475;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<6008;
SELECT COUNT(*) FROM title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.production_year>2010 AND mk.keyword_id<11187;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id=45825;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id<59192;
SELECT COUNT(*) FROM title t,movie_companies mc WHERE t.id=mc.movie_id AND mc.company_id>652 AND mc.company_type_id<2;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_info mi WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND t.kind_id<7 AND t.production_year>2013 AND mi.info_type_id>6;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<21441 AND mc.company_type_id=2;
SELECT COUNT(*) FROM title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.production_year>1984 AND mk.keyword_id<3546;
SELECT COUNT(*) FROM title t,cast_info ci,movie_keyword mk WHERE t.id=ci.movie_id AND t.id=mk.movie_id AND t.production_year>1999 AND ci.person_id<1760213 AND ci.role_id<3;
SELECT COUNT(*) FROM title t,cast_info ci,movie_info mi WHERE t.id=ci.movie_id AND t.id=mi.movie_id AND t.production_year>1975 AND ci.role_id<4;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id=8151;
SELECT COUNT(*) FROM title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.kind_id<3 AND t.production_year>1981 AND mk.keyword_id>782;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id=85125;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_info mi WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND mc.company_id>46 AND mi.info_type_id>7;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id>15661 AND mc.company_type_id=2;
SELECT COUNT(*) FROM title t,movie_info_idx mi_idx,movie_keyword mk WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND t.kind_id<7 AND t.production_year<2012 AND mk.keyword_id>5827;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id<492;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id<89051;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_keyword mk WHERE t.id=mc.movie_id AND t.id=mk.movie_id AND t.kind_id<7 AND mc.company_id>1700;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_keyword mk WHERE t.id=mc.movie_id AND t.id=mk.movie_id AND t.production_year>0 AND mk.keyword_id>411;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<3130 AND mc.company_type_id=1;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<14060 AND mc.company_type_id>1;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<6209 AND mc.company_type_id>1;
SELECT COUNT(*) FROM title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.kind_id<7 AND t.production_year>2013 AND mk.keyword_id<7899;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id>29748;
SELECT COUNT(*) FROM title t,movie_companies mc WHERE t.id=mc.movie_id AND t.production_year<2012 AND mc.company_id=19 AND mc.company_type_id=1;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id=5807;
SELECT COUNT(*) FROM title t,movie_info_idx mi_idx,movie_keyword mk WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND t.kind_id<7 AND t.production_year>2007 AND mi_idx.info_type_id<101 AND mk.keyword_id<23394;
SELECT COUNT(*) FROM title t,movie_info_idx mi_idx,movie_keyword mk WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND t.kind_id<7 AND t.production_year>2001 AND mi_idx.info_type_id>99 AND mk.keyword_id<11403;
SELECT COUNT(*) FROM title t,movie_info_idx mi_idx WHERE t.id=mi_idx.movie_id AND t.kind_id<2 AND t.production_year>1942 AND mi_idx.info_type_id>99;
SELECT COUNT(*) FROM title t,cast_info ci WHERE t.id=ci.movie_id AND ci.person_id<769664;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id>48780 AND mc.company_type_id=2;
SELECT COUNT(*) FROM title t,movie_info mi WHERE t.id=mi.movie_id AND t.kind_id<3 AND mi.info_type_id>13;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id<6052;
SELECT COUNT(*) FROM title t,movie_keyword mk WHERE t.id=mk.movie_id AND mk.keyword_id>397;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>20357;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>647;
SELECT COUNT(*) FROM title t,cast_info ci,movie_keyword mk WHERE t.id=ci.movie_id AND t.id=mk.movie_id AND t.kind_id<7 AND t.production_year>1977 AND mk.keyword_id>309;
SELECT COUNT(*) FROM title t,movie_info mi,movie_info_idx mi_idx WHERE t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.kind_id<7 AND t.production_year<2012 AND mi_idx.info_type_id=101;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id<7075;
SELECT COUNT(*) FROM title t,movie_info_idx mi_idx,movie_keyword mk WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND mi_idx.info_type_id<101 AND mk.keyword_id<359;
SELECT COUNT(*) FROM title t,movie_info mi WHERE t.id=mi.movie_id AND t.kind_id<3 AND t.production_year<1918 AND mi.info_type_id<15;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<149241 AND mc.company_type_id=2;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id>20921;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id<12090;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id<1788221 AND ci.role_id<2;
SELECT COUNT(*) FROM title t,movie_info mi,movie_info_idx mi_idx WHERE t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.kind_id<7 AND t.production_year>1986 AND mi.info_type_id=3;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id=1375;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id<5733;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_info mi WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND t.kind_id<7 AND t.production_year>2010 AND mc.company_id<1910 AND mc.company_type_id>1;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id=200085 AND mc.company_type_id=2;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_info mi WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND t.production_year<2008 AND mc.company_id<173763 AND mc.company_type_id<2 AND mi.info_type_id=6;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id=34640;
SELECT COUNT(*) FROM title t,movie_companies mc WHERE t.id=mc.movie_id AND t.production_year>1896;
SELECT COUNT(*) FROM title t,movie_companies mc,cast_info ci WHERE t.id=mc.movie_id AND t.id=ci.movie_id AND t.production_year<2013 AND mc.company_id<85016 AND mc.company_type_id<2;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id=3584;
SELECT COUNT(*) FROM title t,movie_info_idx mi_idx,movie_keyword mk WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND t.production_year>1991 AND mk.keyword_id<11967;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<70927 AND mc.company_type_id<2;
SELECT COUNT(*) FROM title t,movie_companies mc,cast_info ci WHERE t.id=mc.movie_id AND t.id=ci.movie_id AND mc.company_type_id=1 AND ci.person_id<3861149;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id=29084;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id<3906292;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id=20299;
SELECT COUNT(*) FROM title t,movie_companies mc WHERE t.id=mc.movie_id AND mc.company_id<18156;
SELECT COUNT(*) FROM title t,movie_companies mc WHERE t.id=mc.movie_id AND mc.company_id>82 AND mc.company_type_id=1;
SELECT COUNT(*) FROM title t,cast_info ci,movie_info mi WHERE t.id=ci.movie_id AND t.id=mi.movie_id AND ci.person_id<1801160;
SELECT COUNT(*) FROM title t,movie_info_idx mi_idx,movie_keyword mk WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND mk.keyword_id<5922;
SELECT COUNT(*) FROM title t,movie_keyword mk WHERE t.id=mk.movie_id AND mk.keyword_id<28212;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id<6914;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id<12391;
SELECT COUNT(*) FROM title t,cast_info ci,movie_info_idx mi_idx WHERE t.id=ci.movie_id AND t.id=mi_idx.movie_id AND t.production_year>1976 AND ci.role_id<10;
SELECT COUNT(*) FROM title t,movie_keyword mk WHERE t.id=mk.movie_id AND mk.keyword_id<14526;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id<674;
SELECT COUNT(*) FROM title t,movie_info_idx mi_idx,movie_keyword mk WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND t.production_year>1992 AND mk.keyword_id<3;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id=2788;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<61606 AND mc.company_type_id<2;
SELECT COUNT(*) FROM title t,cast_info ci WHERE t.id=ci.movie_id AND t.kind_id<7 AND t.production_year>2005 AND ci.person_id<2558091;
SELECT COUNT(*) FROM title t,cast_info ci,movie_info_idx mi_idx WHERE t.id=ci.movie_id AND t.id=mi_idx.movie_id AND t.production_year<1969 AND ci.role_id<3;
SELECT COUNT(*) FROM title t,cast_info ci,movie_keyword mk WHERE t.id=ci.movie_id AND t.id=mk.movie_id AND mk.keyword_id>230;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id=39418;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>36535;
SELECT COUNT(*) FROM title t,movie_info_idx mi_idx,movie_keyword mk WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND t.production_year>1982 AND mi_idx.info_type_id<100;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id>20062 AND mc.company_type_id<2;
SELECT COUNT(*) FROM title t,cast_info ci,movie_keyword mk WHERE t.id=ci.movie_id AND t.id=mk.movie_id AND mk.keyword_id>4398;
SELECT COUNT(*) FROM title t,movie_companies mc WHERE t.id=mc.movie_id AND mc.company_id<127102 AND mc.company_type_id=1;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>419;
SELECT COUNT(*) FROM title t,movie_companies mc,cast_info ci WHERE t.id=mc.movie_id AND t.id=ci.movie_id AND t.production_year<2001 AND mc.company_id<166 AND mc.company_type_id>1;
SELECT COUNT(*) FROM title t,cast_info ci,movie_info mi WHERE t.id=ci.movie_id AND t.id=mi.movie_id AND t.kind_id<7 AND t.production_year<1997 AND mi.info_type_id<3;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_info mi WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND mc.company_id<1427 AND mc.company_type_id<2;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id<26843;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id=10635;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id<13046;
SELECT COUNT(*) FROM title t,cast_info ci,movie_keyword mk WHERE t.id=ci.movie_id AND t.id=mk.movie_id AND t.production_year<2006 AND ci.person_id<4037687;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_info_idx mi_idx WHERE t.id=mc.movie_id AND t.id=mi_idx.movie_id AND mc.company_id<55195 AND mc.company_type_id<2;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>5689;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id<4022918;
SELECT COUNT(*) FROM title t,cast_info ci WHERE t.id=ci.movie_id AND t.kind_id<7 AND t.production_year<1996 AND ci.person_id<23733;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<56761;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_info mi WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND mc.company_id>19 AND mi.info_type_id>8;
SELECT COUNT(*) FROM title t,movie_keyword mk WHERE t.id=mk.movie_id AND mk.keyword_id>3483;
SELECT COUNT(*) FROM title t,movie_keyword mk WHERE t.id=mk.movie_id AND mk.keyword_id<8637;
SELECT COUNT(*) FROM title t,movie_info mi,movie_info_idx mi_idx WHERE t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.kind_id<3 AND t.production_year>2005 AND mi.info_type_id=8 AND mi_idx.info_type_id<101;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id>47157;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_keyword mk WHERE t.id=mc.movie_id AND t.id=mk.movie_id AND t.production_year>2013 AND mc.company_id>7851;
SELECT COUNT(*) FROM title t,movie_keyword mk WHERE t.id=mk.movie_id AND mk.keyword_id<3784;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id<2099065 AND ci.role_id<8;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id=49207;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_keyword mk WHERE t.id=mc.movie_id AND t.id=mk.movie_id AND mc.company_id<302 AND mc.company_type_id>1 AND mk.keyword_id<3945;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<16378 AND mc.company_type_id=1;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id<954352;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_info_idx mi_idx WHERE t.id=mc.movie_id AND t.id=mi_idx.movie_id AND t.production_year<2011 AND mc.company_type_id=2;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id<1696471 AND ci.role_id=1;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>4228;
SELECT COUNT(*) FROM title t,movie_companies mc WHERE t.id=mc.movie_id AND t.production_year<1985 AND mc.company_id<7851;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id=452 AND mc.company_type_id=1;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_keyword mk WHERE t.id=mc.movie_id AND t.id=mk.movie_id AND t.kind_id<3 AND t.production_year<1988 AND mc.company_type_id=1;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id<41903;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id=39167;
SELECT COUNT(*) FROM title t,movie_companies mc WHERE t.id=mc.movie_id AND t.kind_id<7 AND mc.company_id>12473;
SELECT COUNT(*) FROM title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.kind_id<7 AND t.production_year<1994 AND mk.keyword_id<1657;
SELECT COUNT(*) FROM title t,movie_info mi,movie_keyword mk WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND t.production_year<2010 AND mi.info_type_id<8;
SELECT COUNT(*) FROM title t,movie_companies mc WHERE t.id=mc.movie_id AND mc.company_id<108655;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_info_idx mi_idx WHERE t.id=mc.movie_id AND t.id=mi_idx.movie_id AND mc.company_id>1376 AND mc.company_type_id=1 AND mi_idx.info_type_id<100;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id=122 AND mc.company_type_id=1;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<71473 AND mc.company_type_id=1;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id<2175543;
SELECT COUNT(*) FROM title t,cast_info ci WHERE t.id=ci.movie_id AND ci.person_id<1327705 AND ci.role_id<3;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>26039;
SELECT COUNT(*) FROM title t,movie_info_idx mi_idx,movie_keyword mk WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND mi_idx.info_type_id>99 AND mk.keyword_id<2172;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<83375 AND mc.company_type_id<2;
SELECT COUNT(*) FROM title t,movie_info mi,movie_info_idx mi_idx WHERE t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.production_year>2012 AND mi_idx.info_type_id<101;
SELECT COUNT(*) FROM title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.kind_id<3 AND mk.keyword_id<2230;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id<915566;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_info_idx mi_idx WHERE t.id=mc.movie_id AND t.id=mi_idx.movie_id AND t.production_year>1991;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>2359;
SELECT COUNT(*) FROM title t,cast_info ci WHERE t.id=ci.movie_id AND ci.person_id<1656437 AND ci.role_id=1;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id>11603;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_keyword mk WHERE t.id=mc.movie_id AND t.id=mk.movie_id AND t.production_year>1982 AND mc.company_id<452 AND mc.company_type_id=1;
SELECT COUNT(*) FROM title t,movie_keyword mk WHERE t.id=mk.movie_id AND mk.keyword_id<6366;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id<2911839;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id<26725;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_keyword mk WHERE t.id=mc.movie_id AND t.id=mk.movie_id AND mc.company_id=27 AND mc.company_type_id=1;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<40999 AND mc.company_type_id=1;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>89592;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id<18407;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id>7640;
SELECT COUNT(*) FROM title t,movie_companies mc WHERE t.id=mc.movie_id AND t.kind_id<7 AND mc.company_id>28339;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<738 AND mc.company_type_id<2;
SELECT COUNT(*) FROM title t,movie_companies mc WHERE t.id=mc.movie_id AND mc.company_id<10112;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id=14185 AND mc.company_type_id>1;
SELECT COUNT(*) FROM title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.production_year>1968 AND mk.keyword_id<5683;
SELECT COUNT(*) FROM title t,movie_info_idx mi_idx,movie_keyword mk WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND mk.keyword_id<36275;
SELECT COUNT(*) FROM title t,movie_companies mc,cast_info ci WHERE t.id=mc.movie_id AND t.id=ci.movie_id AND mc.company_id<3015 AND ci.role_id=1;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<1841 AND mc.company_type_id=2;
SELECT COUNT(*) FROM title t,cast_info ci WHERE t.id=ci.movie_id AND t.production_year>1923 AND ci.person_id<2597757;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id=19337;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id>22340 AND mc.company_type_id>1;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id=13533;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id=1049 AND mc.company_type_id>1;
SELECT COUNT(*) FROM title t,movie_info mi,movie_info_idx mi_idx WHERE t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.kind_id<2 AND mi_idx.info_type_id>99;
SELECT COUNT(*) FROM title t,movie_info mi WHERE t.id=mi.movie_id AND t.production_year<1994 AND mi.info_type_id=18;
SELECT COUNT(*) FROM title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.production_year<2005 AND mk.keyword_id<93374;
SELECT COUNT(*) FROM title t,movie_companies mc,movie_info mi WHERE t.id=mc.movie_id AND t.id=mi.movie_id AND mc.company_id<92918 AND mc.company_type_id=2;
SELECT COUNT(*) FROM title t,cast_info ci,movie_info mi WHERE t.id=ci.movie_id AND t.id=mi.movie_id AND ci.person_id<618546 AND mi.info_type_id>2;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id=92467;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<3039 AND mc.company_type_id>1;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id=120958;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id<116606 AND mc.company_type_id<2;
SELECT COUNT(*) FROM movie_companies mc WHERE mc.company_id=71000;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id<2835974;
SELECT COUNT(*) FROM cast_info ci WHERE ci.person_id<856996 AND ci.role_id=1;
SELECT COUNT(*) FROM title t,movie_info mi WHERE t.id=mi.movie_id AND t.production_year<1996 AND mi.info_type_id<2;
SELECT COUNT(*) FROM movie_keyword mk WHERE mk.keyword_id=34362;
SELECT COUNT(*) FROM title t,movie_info mi WHERE t.id=mi.movie_id AND t.production_year>1915 AND mi.info_type_id>7;
SELECT COUNT(*) FROM title t,movie_info mi,movie_info_idx mi_idx WHERE t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.production_year<1999 AND mi.info_type_id=1 AND mi_idx.info_type_id=100;
SELECT COUNT(*) FROM title t,movie_info_idx mi_idx,movie_keyword mk WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND mi_idx.info_type_id=99 AND mk.keyword_id<12015;
SELECT COUNT(*) FROM title t,movie_keyword mk WHERE t.id=mk.movie_id AND t.kind_id<7 AND t.production_year>1987 AND mk.keyword_id>1096;
